### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by RayyanNafees** [gamemaker1/micro-plugin-prettier#1]
# Plugin not installable by your installation code in the readme `micro --plugin install prettier`

![image](https://github.com/gamemaker1/micro-plugin-prettier/assets/59685062/083d5f8e-e9e1-4553-9681-067edf38fa85)

**Comment by gamemaker1** [comment]
Hi @RayyanNafees,

Could you please add the following line to your micro config (`~/.config/micro/settings.json`) and then try installing the plugin again? If this works I'll add it to the readme too.

```json
{
  // ....,
  "pluginrepos": ["https://raw.githubusercontent.com/gamemaker1/micro-plugin-prettier/main/repo.json"]
}
```

Thanks,
Vedant

**Comment by RayyanNafees** [comment]
# Installed but not working

The plugin did installed and loaded in the micro editor
![image](https://github.com/gamemaker1/micro-plugin-prettier/assets/59685062/b63cde84-0abd-4bd8-a18c-1fcd7df949f0)

But it doesn't seem to function while saving
![image](https://github.com/gamemaker1/micro-plugin-prettier/assets/59685062/667b0a36-9c5a-4f35-acbd-64abaf84fc63)


And when opening `Ctrl + E` > `log` then there's nothing... logs are empty

**Comment by gamemaker1** [comment]
You'll need to install prettier somewhere in your PATH, you could do that with `npm install --global prettier`.
